### ISSUE TITLE
Failed to load the coffee-refactor package

### ISSUE THREAD

**Issue by kmdavis** [minodisk/coffee-refactor#8]
[Enter steps to reproduce below:]
1. open atom

**Atom Version**: 0.198.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [coffee-refactor](https://github.com/minodisk/coffee-refactor) package, v0.6.2
### Stack Trace

Failed to load the coffee-refactor package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/kdavis/.atom/packages/coffee-refactor/lib/notification_view.coffee:9:199)
  at /Users/kdavis/.atom/packages/coffee-refactor/lib/notification_view.coffee:9:3
  at Object.<anonymous> (/Users/kdavis/.atom/packages/coffee-refactor/lib/notification_view.coffee:80:5)
  at Object.<anonymous> (/Users/kdavis/.atom/packages/coffee-refactor/lib/notification_view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/kdavis/.atom/packages/coffee-refactor/lib/coffee_refactor.coffee:2:20)
  at Object.<anonymous> (/Users/kdavis/.atom/packages/coffee-refactor/lib/coffee_refactor.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:711:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:354:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:324:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:620:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:38:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "*.pyc"
    ],
    "disabledPackages": [
      "snippets",
      "atomatigit",
      "tabs",
      "tree-view",
      "tabs",
      "tree-view",
      "linter-flake8",
      "tree-view-filter"
    ]
  },
  "coffee-refactor": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-color-highlight, v3.0.9
atom-handlebars, v0.5.0
atom-python-debugger, v0.2.2
auto-update-packages, v0.2.2
autocomplete-plus, v2.13.1
change-case, v0.5.1
coffee-compile, v0.14.0
coffee-refactor, v0.6.2
color-picker, v1.7.0
docblockr, v0.6.3
emmet, v2.3.9
file-icons, v1.5.5
filetype-color, v0.1.4
format-sql, v0.2.0
git-history, v2.5.0
git-log, v0.3.0
git-tab-status, v1.7.0
highlight-cov, v0.1.0
highlight-line, v0.10.2
highlight-selected, v0.9.2
js-refactor, v0.3.0
language-python-django, v0.3.1
linter, v0.12.2
linter-coffeelint, v0.2.3
minimap, v4.8.0
minimap-color-highlight, v4.1.3
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.3
minimap-selection, v4.2.0
notebook, v0.4.0
open-last-project, v0.4.1
refactor, v0.4.1
regex-railroad-diagram, v0.7.4
script, v2.22.0
sublime-tabs, v0.5.6
symbols-tree-view, v0.9.2
view-tail-large-files, v0.1.14

# Dev
No dev packages
```

**Comment by minodisk** [comment]
See #9
